### ISSUE TITLE
Issue when loading In-Shop Clothes Dataset

### ISSUE THREAD

**Issue by stoneyang** [Confusezius/Deep-Metric-Learning-Baselines#11]
Hi, @Confusezius , 

Thanks for your excellent code and for sharing it! 

When running 
```
python3.6 Standard_Training.py --gpu 0 --savename resnet_inshop_margin_dist  --dataset in-shop --n_epochs 40 --tau 25 --loss marginloss --sampling distance
```
the following issue raises and I've put the dataset under `Datasets` directory and the data is fine.
```
Getting pretrained weights...
Done.
MARGINLOSS Setup for RESNET50 with DISTANCE sampling on IN-SHOP complete with #weights: 23770304
Traceback (most recent call last):
  File "Standard_Training.py", line 161, in <module>
    dataloaders      = data.give_dataloaders(opt.dataset, opt)
  File "/home/code/Deep-Metric-Learning-Baselines/datasets.py", line 50, in give_dataloaders
    datasets = give_InShop_datasets(opt)
  File "/home/code/Deep-Metric-Learning-Baselines/datasets.py", line 280, in give_InShop_datasets
    train_dataset     = BaseTripletDataset(train_image_dict, opt,   samples_per_class=opt.samples_per_class)
  File "/home/code/Deep-Metric-Learning-Baselines/datasets.py", line 398, in __init__
    transforms.RandomHorizontalFlip(0.5)])
TypeError: object() takes no parameters
```
So, could u shed me some light? Thanks!

**Comment by Confusezius** [comment]
Hi there! Could it be that you are using an older PyTorch/Torchvision version? E.g. what is described here: https://discuss.pytorch.org/t/error-on-transforms-randomhorizontalflip-p-0-5/14724 ?

**Comment by stoneyang** [comment]
Thanks for your hint! You are my life saver!  @Confusezius
